export const TRANSACTION_CATEGORIES = [
  { id: 'housing', icon: '🏠', en: 'Housing', pt: 'Moradia' },
  { id: 'groceries', icon: '🛒', en: 'Groceries', pt: 'Alimentação' },
  { id: 'transport', icon: '🚗', en: 'Transportation', pt: 'Transporte' },
  { id: 'utilities', icon: '⚡', en: 'Utilities', pt: 'Contas Básicas' },
  { id: 'phone', icon: '📱', en: 'Phone & Internet', pt: 'Celular e Internet' },
  { id: 'subscriptions', icon: '📺', en: 'Subscriptions', pt: 'Assinaturas' },
  { id: 'health', icon: '🏥', en: 'Health', pt: 'Saúde' },
  { id: 'insurance', icon: '🛡️', en: 'Insurance', pt: 'Seguros' },
  { id: 'dining', icon: '🍕', en: 'Dining Out', pt: 'Restaurantes' },
  { id: 'entertainment', icon: '🎬', en: 'Entertainment', pt: 'Entretenimento' },
  { id: 'shopping', icon: '🛍️', en: 'Shopping', pt: 'Compras' },
  { id: 'education', icon: '📚', en: 'Education', pt: 'Educação' },
  { id: 'personal', icon: '💅', en: 'Personal Care', pt: 'Cuidados Pessoais' },
  { id: 'salary', icon: '💰', en: 'Salary', pt: 'Salário' },
  { id: 'freelance', icon: '💻', en: 'Freelance', pt: 'Freelance' },
  { id: 'investment', icon: '📈', en: 'Investment', pt: 'Investimento' },
  { id: 'gift', icon: '🎁', en: 'Gift', pt: 'Presente' },
  { id: 'debt', icon: '💳', en: 'Debt Payment', pt: 'Pagamento de Dívida' },
  { id: 'savings', icon: '🏦', en: 'Savings', pt: 'Poupança' },
  { id: 'taxes', icon: '🏛️', en: 'Taxes', pt: 'Impostos' },
  { id: 'childcare', icon: '👶', en: 'Childcare', pt: 'Crianças' },
  { id: 'pets', icon: '🐾', en: 'Pets', pt: 'Animais' },
  { id: 'other', icon: '📌', en: 'Other', pt: 'Outros' },
] as const;

export type CategoryId = typeof TRANSACTION_CATEGORIES[number]['id'];

export const COMMON_BILL_TEMPLATES = [
  { name_en: 'Rent', name_pt: 'Aluguel', category: 'housing' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Electric Bill', name_pt: 'Conta de Luz', category: 'utilities' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Water Bill', name_pt: 'Conta de Água', category: 'utilities' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Internet', name_pt: 'Internet', category: 'phone' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Phone Plan', name_pt: 'Plano de Celular', category: 'phone' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Car Payment', name_pt: 'Parcela do Carro', category: 'transport' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Car Insurance', name_pt: 'Seguro do Carro', category: 'insurance' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Health Insurance', name_pt: 'Plano de Saúde', category: 'health' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Gym', name_pt: 'Academia', category: 'health' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Streaming (Netflix, etc)', name_pt: 'Streaming (Netflix, etc)', category: 'subscriptions' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Student Loan', name_pt: 'Empréstimo Estudantil', category: 'education' as CategoryId, frequency: 'Monthly' as const },
  { name_en: 'Childcare', name_pt: 'Creche', category: 'childcare' as CategoryId, frequency: 'Monthly' as const },
] as const;
